# This is a basic workflow to help you get started with Actions

name: self-hosted-windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#  pull_request:
 #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted,windows,x64]
    env:
      environmentUrl: https//dreamingincrm.crm6.dynamics.com
      userName: "actionuser@dreamingincrm.onmicrosoft.com"
      applicationId: "e605bea5-f749-4f51-8508-8c6891d9f8dc"
      solution: "GitHubActionsDemo"
      timezone: "CEST"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - id: who-am-i
        name: Connecting to ${{ env.envrionmentUrl }} as ${{ env.userName}}
        uses: microsoft/powerplatform-actions/who-am-i@v0.1.8
        with:
           environment-url: ${{ env.environmentUrl }}
           user-name: ${{ env.userName }}
           password-secret: ${{ secrets.password }}

      # Runs a single command using the runners shell
    #  - name: Run a one-line script
    #    run: echo Hello, world!

      # Runs a set of commands using the runners shell
    #  - name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
       #   echo test, and deploy your project.
