name: temp

on:
  workflow_dispatch:

jobs:
  build:
    #runs-on: [self-hosted, windows, x64]
    runs-on: windows-latest
    env:
      environmentUrl: https://dreamingincrm.crm6.dynamics.com
      userName: "actionsuser@dreamingincrm.onmicrosoft.com"
      applicationId: "e605bea5-f749-4f51-8508-8c6891d9f8dc"
      solution: "GitHubActionsDemo"
      timeZone: "AUS Eastern Standard Time"
      PacCli.PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
                
      - id: increment-solution-version
        name: Bump ${{ env.solution }} version to ${{ github.run_number }}
        uses: microsoft/powerplatform-actions/update-solution-version@b24403b
        with:
          strategy: "gittags"
          
      - id: solution-version
        name: Getting version information for ${{ env.solution }}
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: "Solutions/${{ env.solution }}/src/Other/Solution.xml"
          xpath: "//ImportExportXml/SolutionManifest/Version"
          
      - id: branch-name
        name: Set Branch Name variable
        run: |
          echo "::set-output name=branchName::${{ env.solution }}_${{ steps.solution-version.outputs.info }}"

      - id: create-solution-branch
        name: Create ${{ steps.branch-name.outputs.branchName }} branch
        uses: microsoft/powerplatform-actions/branch-solution@v0.1.8
        with:
          solution-folder: "Solutions/${{ env.solution }}"
          solution-target-folder: "Solutions/${{ env.solution }}"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-name: ${{ steps.branch-name.outputs.branchName }}

      - uses: octokit/request-action@v2.x
        name: Create PR for branch ${{ steps.branch-name.outputs.branchName }}
        id: create_pr
        with:
          owner: "rajyraman"
          repo: ${{ github.repository }}
          route: POST /repos/:repo/pulls
          title: ${{ steps.branch-name.outputs.branchName }}
          head: ${{ steps.branch-name.outputs.branchName }}
          base: "main"
          maintainer_can_modify: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
